# Generated by Django 2.2.14 on 2023-01-19 13:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0009_notfication'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notfication',
            new_name='Notification',
        ),
    ]
