# Generated by Django 2.2.14 on 2023-01-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0014_notification_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/post_photos')),
            ],
        ),
    ]
