# Generated by Django 2.2.14 on 2023-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ManyToManyField(blank=True, to='social.Image'),
        ),
    ]
