# Generated by Django 2.2.14 on 2023-01-30 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_auto_20230130_2250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='social.Tag'),
        ),
    ]
