# Generated by Django 2.2.14 on 2023-02-06 02:22

from django.db import migrations, models
import social.validators


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20230205_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='video/%y', validators=[social.validators.file_size])),
            ],
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=models.ManyToManyField(blank=True, to='social.Video'),
        ),
    ]
